version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Steradian
      POSTGRES_PASSWORD: Steradian
      POSTGRES_DB: dbSteradian
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
